

__author__ = 'ale'

from PyQt4 import QtGui
from PyQt4 import QtCore
from PyQt4.QtGui import QLineEdit
from PyQt4.QtGui import QMessageBox
from ventanaUsuario import VentanaUsuario
from PyQt4.QtGui import QMainWindow
from Controlador.controladorventanaprincipal import ControladorVentanaPrincipal
from ventanahemocultivo import VentanaHemocultivo
from ventanaMuestra import VentanaMuestra
from PyQt4.QtCore import QSize
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class VentanaPrincipal(QMainWindow):

    def __init__(self):
        QMainWindow.__init__(self)
        self.setupUi(self)

    def setupUi(self, MainWindow):

        self.direccionDeImagenes = "/home/pi/TestHemo1/img/"
        #self.direccionDeImagenes = "/home/ale/PycharmProjects/TestHemo1/img/"
        self.diccionarioPositivo = []
        self.diccionarioNegativo  = []
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1360, 792)
        MainWindow.setWindowFlags(QtCore.Qt.WindowStaysOnBottomHint)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setBaseSize(QtCore.QSize(-1, 0))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.ContenedorGeneral = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ContenedorGeneral.sizePolicy().hasHeightForWidth())
        self.ContenedorGeneral.setSizePolicy(sizePolicy)
        self.ContenedorGeneral.setBaseSize(QtCore.QSize(-1, 0))
        self.ContenedorGeneral.setObjectName(_fromUtf8("ContenedorGeneral"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.ContenedorGeneral)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.groupBox_3 = QtGui.QGroupBox(self.ContenedorGeneral)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.GLogIn = QtGui.QGroupBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GLogIn.sizePolicy().hasHeightForWidth())
        self.GLogIn.setSizePolicy(sizePolicy)
        self.GLogIn.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.GLogIn.setFont(font)
        self.GLogIn.setStyleSheet(_fromUtf8(""))
        self.GLogIn.setObjectName(_fromUtf8("GLogIn"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.GLogIn)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_103 = QtGui.QLabel(self.GLogIn)
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.verticalLayout_2.addWidget(self.label_103)
        self.lineEdit = QtGui.QLineEdit(self.GLogIn)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.label_104 = QtGui.QLabel(self.GLogIn)
        self.label_104.setObjectName(_fromUtf8("label_104"))
        self.verticalLayout_2.addWidget(self.label_104)
        self.lineEdit_2 = QtGui.QLineEdit(self.GLogIn)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.Submit = QtGui.QPushButton(self.GLogIn)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.Submit.setFont(font)
        self.Submit.setObjectName(_fromUtf8("Submit"))
        self.verticalLayout_2.addWidget(self.Submit)
        self.verticalLayout_3.addWidget(self.GLogIn)
        self.Settings = QtGui.QGroupBox(self.groupBox_3)
        self.Settings.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Settings.sizePolicy().hasHeightForWidth())
        self.Settings.setSizePolicy(sizePolicy)
        self.Settings.setMaximumSize(QtCore.QSize(16777215, 200))
        self.Settings.setToolTip(_fromUtf8(""))
        self.Settings.setAutoFillBackground(False)
        self.Settings.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Settings.setTitle(_fromUtf8(""))
        self.Settings.setCheckable(False)
        self.Settings.setChecked(False)
        self.Settings.setObjectName(_fromUtf8("Settings"))
        self.verticalLayout_55 = QtGui.QVBoxLayout(self.Settings)
        self.verticalLayout_55.setObjectName(_fromUtf8("verticalLayout_55"))
        self.BInformesSettings = QtGui.QPushButton(self.Settings)
        self.BInformesSettings.setObjectName(_fromUtf8("BInformesSettings"))
        self.verticalLayout_55.addWidget(self.BInformesSettings)
        self.BUsuariosSettings = QtGui.QPushButton(self.Settings)
        self.BUsuariosSettings.setObjectName(_fromUtf8("BUsuariosSettings"))
        self.verticalLayout_55.addWidget(self.BUsuariosSettings)
        self.BLogOutSettings = QtGui.QPushButton(self.Settings)
        self.BLogOutSettings.setObjectName(_fromUtf8("BLogOutSettings"))
        self.verticalLayout_55.addWidget(self.BLogOutSettings)
        self.verticalLayout_3.addWidget(self.Settings)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.GTemperature = QtGui.QGroupBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GTemperature.sizePolicy().hasHeightForWidth())
        self.GTemperature.setSizePolicy(sizePolicy)
        self.GTemperature.setMinimumSize(QtCore.QSize(0, 80))
        self.GTemperature.setMaximumSize(QtCore.QSize(16777215, 200))
        self.GTemperature.setTitle(_fromUtf8(""))
        self.GTemperature.setObjectName(_fromUtf8("GTemperature"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.GTemperature)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.GTemperature)
        self.label.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777214))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tlwg Typist"))
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.lcdNumber = QtGui.QLCDNumber(self.GTemperature)

        self.lcdNumber.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        self.lcdNumber.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.verticalLayout_5.addWidget(self.lcdNumber)
        self.verticalLayout_3.addWidget(self.GTemperature)
        self.horizontalLayout_12.addWidget(self.groupBox_3)
        self.Grilla = QtGui.QGroupBox(self.ContenedorGeneral)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Grilla.sizePolicy().hasHeightForWidth())
        self.Grilla.setSizePolicy(sizePolicy)
        self.Grilla.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Grilla.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Grilla.setTitle(_fromUtf8(""))
        self.Grilla.setObjectName(_fromUtf8("Grilla"))
        self.verticalLayout = QtGui.QVBoxLayout(self.Grilla)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.Gcelda_97 = QtGui.QGroupBox(self.Grilla)
        self.Gcelda_97.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_97.sizePolicy().hasHeightForWidth())
        self.Gcelda_97.setSizePolicy(sizePolicy)
        self.Gcelda_97.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_97.setTitle(_fromUtf8(""))
        self.Gcelda_97.setObjectName(_fromUtf8("Gcelda_97"))
        self.gridLayout = QtGui.QGridLayout(self.Gcelda_97)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.c1 = QtGui.QPushButton(self.Gcelda_97)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c1.sizePolicy().hasHeightForWidth())
        self.c1.setSizePolicy(sizePolicy)
        self.c1.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c1.setFont(font)
        self.c1.setStyleSheet(_fromUtf8("border-image: url("+self.direccionDeImagenes+"cGris.png) 0 0 0 0 stretch stretch;"))
        self.c1.setObjectName(_fromUtf8("c1"))
        self.gridLayout.addWidget(self.c1, 0, 0, 2, 1)
        self.label_3 = QtGui.QLabel(self.Gcelda_97)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.Gcelda_97)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.Gcelda_97)
        self.Gcelda_101 = QtGui.QGroupBox(self.Grilla)
        self.Gcelda_101.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_101.sizePolicy().hasHeightForWidth())
        self.Gcelda_101.setSizePolicy(sizePolicy)
        self.Gcelda_101.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_101.setTitle(_fromUtf8(""))
        self.Gcelda_101.setObjectName(_fromUtf8("Gcelda_101"))
        self.gridLayout_5 = QtGui.QGridLayout(self.Gcelda_101)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_4 = QtGui.QLabel(self.Gcelda_101)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.Gcelda_101)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 1, 1, 1, 1)
        self.c2 = QtGui.QPushButton(self.Gcelda_101)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c2.sizePolicy().hasHeightForWidth())
        self.c2.setSizePolicy(sizePolicy)
        self.c2.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c2.setFont(font)
        self.c2.setStyleSheet(_fromUtf8("border-image: url("+self.direccionDeImagenes+"cGris.png) 0 0 0 0 stretch stretch;"))
        self.c2.setObjectName(_fromUtf8("c2"))
        self.gridLayout_5.addWidget(self.c2, 0, 0, 2, 1)
        self.horizontalLayout.addWidget(self.Gcelda_101)
        self.Gcelda_100 = QtGui.QGroupBox(self.Grilla)
        self.Gcelda_100.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_100.sizePolicy().hasHeightForWidth())
        self.Gcelda_100.setSizePolicy(sizePolicy)
        self.Gcelda_100.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_100.setTitle(_fromUtf8(""))
        self.Gcelda_100.setObjectName(_fromUtf8("Gcelda_100"))
        self.gridLayout_4 = QtGui.QGridLayout(self.Gcelda_100)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.c3 = QtGui.QPushButton(self.Gcelda_100)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c3.sizePolicy().hasHeightForWidth())
        self.c3.setSizePolicy(sizePolicy)
        self.c3.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c3.setFont(font)
        self.c3.setStyleSheet(_fromUtf8("border-image: url("+self.direccionDeImagenes+"cGris.png) 0 0 0 0 stretch stretch;"))
        self.c3.setObjectName(_fromUtf8("c3"))
        self.gridLayout_4.addWidget(self.c3, 0, 0, 2, 1)
        self.label_6 = QtGui.QLabel(self.Gcelda_100)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.Gcelda_100)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.Gcelda_100)
        self.Gcelda_99 = QtGui.QGroupBox(self.Grilla)
        self.Gcelda_99.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_99.sizePolicy().hasHeightForWidth())
        self.Gcelda_99.setSizePolicy(sizePolicy)
        self.Gcelda_99.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_99.setTitle(_fromUtf8(""))
        self.Gcelda_99.setObjectName(_fromUtf8("Gcelda_99"))
        self.gridLayout_3 = QtGui.QGridLayout(self.Gcelda_99)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.c4 = QtGui.QPushButton(self.Gcelda_99)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c4.sizePolicy().hasHeightForWidth())
        self.c4.setSizePolicy(sizePolicy)
        self.c4.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c4.setFont(font)
        self.c4.setStyleSheet(_fromUtf8("border-image: url("+self.direccionDeImagenes+"cGris.png) 0 0 0 0 stretch stretch;"))
        self.c4.setObjectName(_fromUtf8("c4"))
        self.gridLayout_3.addWidget(self.c4, 0, 0, 2, 1)
        self.label_8 = QtGui.QLabel(self.Gcelda_99)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.Gcelda_99)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.Gcelda_99)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.Gcelda_98 = QtGui.QGroupBox(self.Grilla)
        self.Gcelda_98.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_98.sizePolicy().hasHeightForWidth())
        self.Gcelda_98.setSizePolicy(sizePolicy)
        self.Gcelda_98.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_98.setTitle(_fromUtf8(""))
        self.Gcelda_98.setObjectName(_fromUtf8("Gcelda_98"))
        self.gridLayout_2 = QtGui.QGridLayout(self.Gcelda_98)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.Gcelda_98)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.Gcelda_98)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 1, 1, 1, 1)
        self.c5 = QtGui.QPushButton(self.Gcelda_98)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c5.sizePolicy().hasHeightForWidth())
        self.c5.setSizePolicy(sizePolicy)
        self.c5.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c5.setFont(font)
        self.c5.setStyleSheet(_fromUtf8("border-image: url("+self.direccionDeImagenes+"cGris.png) 0 0 0 0 stretch stretch;"))
        self.c5.setObjectName(_fromUtf8("c5"))
        self.gridLayout_2.addWidget(self.c5, 0, 0, 2, 1)
        self.horizontalLayout_2.addWidget(self.Gcelda_98)
        self.Gcelda_102 = QtGui.QGroupBox(self.Grilla)
        self.Gcelda_102.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_102.sizePolicy().hasHeightForWidth())
        self.Gcelda_102.setSizePolicy(sizePolicy)
        self.Gcelda_102.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_102.setTitle(_fromUtf8(""))
        self.Gcelda_102.setObjectName(_fromUtf8("Gcelda_102"))
        self.gridLayout_6 = QtGui.QGridLayout(self.Gcelda_102)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.c6 = QtGui.QPushButton(self.Gcelda_102)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c6.sizePolicy().hasHeightForWidth())
        self.c6.setSizePolicy(sizePolicy)
        self.c6.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c6.setFont(font)
        self.c6.setStyleSheet(_fromUtf8("border-image: url("+self.direccionDeImagenes+"cGris.png) 0 0 0 0 stretch stretch;"))
        self.c6.setObjectName(_fromUtf8("c6"))
        self.gridLayout_6.addWidget(self.c6, 0, 0, 2, 1)
        self.label_12 = QtGui.QLabel(self.Gcelda_102)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.Gcelda_102)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 1, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.Gcelda_102)
        self.Gcelda_103 = QtGui.QGroupBox(self.Grilla)
        self.Gcelda_103.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_103.sizePolicy().hasHeightForWidth())
        self.Gcelda_103.setSizePolicy(sizePolicy)
        self.Gcelda_103.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_103.setTitle(_fromUtf8(""))
        self.Gcelda_103.setObjectName(_fromUtf8("Gcelda_103"))
        self.gridLayout_7 = QtGui.QGridLayout(self.Gcelda_103)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.c7 = QtGui.QPushButton(self.Gcelda_103)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c7.sizePolicy().hasHeightForWidth())
        self.c7.setSizePolicy(sizePolicy)
        self.c7.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c7.setFont(font)
        self.c7.setStyleSheet(_fromUtf8("border-image: url("+self.direccionDeImagenes+"cGris.png) 0 0 0 0 stretch stretch;"))
        self.c7.setObjectName(_fromUtf8("c7"))
        self.gridLayout_7.addWidget(self.c7, 0, 0, 2, 1)
        self.label_14 = QtGui.QLabel(self.Gcelda_103)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_7.addWidget(self.label_14, 0, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.Gcelda_103)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_7.addWidget(self.label_15, 1, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.Gcelda_103)
        self.Gcelda_104 = QtGui.QGroupBox(self.Grilla)
        self.Gcelda_104.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_104.sizePolicy().hasHeightForWidth())
        self.Gcelda_104.setSizePolicy(sizePolicy)
        self.Gcelda_104.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_104.setTitle(_fromUtf8(""))
        self.Gcelda_104.setObjectName(_fromUtf8("Gcelda_104"))
        self.gridLayout_8 = QtGui.QGridLayout(self.Gcelda_104)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_16 = QtGui.QLabel(self.Gcelda_104)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_8.addWidget(self.label_16, 0, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.Gcelda_104)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_8.addWidget(self.label_17, 1, 1, 1, 1)
        self.c8 = QtGui.QPushButton(self.Gcelda_104)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c8.sizePolicy().hasHeightForWidth())
        self.c8.setSizePolicy(sizePolicy)
        self.c8.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c8.setFont(font)
        self.c8.setStyleSheet(_fromUtf8("border-image: url("+self.direccionDeImagenes+"cGris.png) 0 0 0 0 stretch stretch;"))
        self.c8.setObjectName(_fromUtf8("c8"))
        self.gridLayout_8.addWidget(self.c8, 0, 0, 2, 1)
        self.horizontalLayout_2.addWidget(self.Gcelda_104)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.Gcelda_105 = QtGui.QGroupBox(self.Grilla)
        self.Gcelda_105.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_105.sizePolicy().hasHeightForWidth())
        self.Gcelda_105.setSizePolicy(sizePolicy)
        self.Gcelda_105.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_105.setTitle(_fromUtf8(""))
        self.Gcelda_105.setObjectName(_fromUtf8("Gcelda_105"))
        self.gridLayout_9 = QtGui.QGridLayout(self.Gcelda_105)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.c9 = QtGui.QPushButton(self.Gcelda_105)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c9.sizePolicy().hasHeightForWidth())
        self.c9.setSizePolicy(sizePolicy)
        self.c9.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c9.setFont(font)
        self.c9.setStyleSheet(_fromUtf8("border-image: url("+self.direccionDeImagenes+"cGris.png) 0 0 0 0 stretch stretch;"))
        self.c9.setObjectName(_fromUtf8("c9"))
        self.gridLayout_9.addWidget(self.c9, 0, 0, 2, 1)
        self.label_18 = QtGui.QLabel(self.Gcelda_105)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_9.addWidget(self.label_18, 0, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.Gcelda_105)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_9.addWidget(self.label_19, 1, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.Gcelda_105)
        self.Gcelda_106 = QtGui.QGroupBox(self.Grilla)
        self.Gcelda_106.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_106.sizePolicy().hasHeightForWidth())
        self.Gcelda_106.setSizePolicy(sizePolicy)
        self.Gcelda_106.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_106.setTitle(_fromUtf8(""))
        self.Gcelda_106.setObjectName(_fromUtf8("Gcelda_106"))
        self.gridLayout_10 = QtGui.QGridLayout(self.Gcelda_106)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.c10 = QtGui.QPushButton(self.Gcelda_106)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c10.sizePolicy().hasHeightForWidth())
        self.c10.setSizePolicy(sizePolicy)
        self.c10.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c10.setFont(font)
        self.c10.setStyleSheet(_fromUtf8("border-image: url("+self.direccionDeImagenes+"cGris.png) 0 0 0 0 stretch stretch;"))
        self.c10.setObjectName(_fromUtf8("c10"))
        self.gridLayout_10.addWidget(self.c10, 0, 0, 2, 1)
        self.label_20 = QtGui.QLabel(self.Gcelda_106)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_10.addWidget(self.label_20, 0, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.Gcelda_106)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_10.addWidget(self.label_21, 1, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.Gcelda_106)
        self.Gcelda_107 = QtGui.QGroupBox(self.Grilla)
        self.Gcelda_107.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_107.sizePolicy().hasHeightForWidth())
        self.Gcelda_107.setSizePolicy(sizePolicy)
        self.Gcelda_107.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_107.setTitle(_fromUtf8(""))
        self.Gcelda_107.setObjectName(_fromUtf8("Gcelda_107"))
        self.gridLayout_11 = QtGui.QGridLayout(self.Gcelda_107)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.c11 = QtGui.QPushButton(self.Gcelda_107)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c11.sizePolicy().hasHeightForWidth())
        self.c11.setSizePolicy(sizePolicy)
        self.c11.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c11.setFont(font)
        self.c11.setStyleSheet(_fromUtf8("border-image: url("+self.direccionDeImagenes+"cGris.png) 0 0 0 0 stretch stretch;"))
        self.c11.setObjectName(_fromUtf8("c11"))
        self.gridLayout_11.addWidget(self.c11, 0, 0, 2, 1)
        self.label_22 = QtGui.QLabel(self.Gcelda_107)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_11.addWidget(self.label_22, 0, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.Gcelda_107)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_11.addWidget(self.label_23, 1, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.Gcelda_107)
        self.Gcelda_108 = QtGui.QGroupBox(self.Grilla)
        self.Gcelda_108.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_108.sizePolicy().hasHeightForWidth())
        self.Gcelda_108.setSizePolicy(sizePolicy)
        self.Gcelda_108.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_108.setTitle(_fromUtf8(""))
        self.Gcelda_108.setObjectName(_fromUtf8("Gcelda_108"))
        self.gridLayout_12 = QtGui.QGridLayout(self.Gcelda_108)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.c12 = QtGui.QPushButton(self.Gcelda_108)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c12.sizePolicy().hasHeightForWidth())
        self.c12.setSizePolicy(sizePolicy)
        self.c12.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c12.setFont(font)
        self.c12.setStyleSheet(_fromUtf8("border-image: url("+self.direccionDeImagenes+"cGris.png) 0 0 0 0 stretch stretch;"))
        self.c12.setObjectName(_fromUtf8("c12"))
        self.gridLayout_12.addWidget(self.c12, 0, 0, 2, 1)
        self.label_24 = QtGui.QLabel(self.Gcelda_108)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_12.addWidget(self.label_24, 0, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.Gcelda_108)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_12.addWidget(self.label_25, 1, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.Gcelda_108)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.Gcelda_109 = QtGui.QGroupBox(self.Grilla)
        self.Gcelda_109.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_109.sizePolicy().hasHeightForWidth())
        self.Gcelda_109.setSizePolicy(sizePolicy)
        self.Gcelda_109.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_109.setTitle(_fromUtf8(""))
        self.Gcelda_109.setObjectName(_fromUtf8("Gcelda_109"))
        self.gridLayout_13 = QtGui.QGridLayout(self.Gcelda_109)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.c13 = QtGui.QPushButton(self.Gcelda_109)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c13.sizePolicy().hasHeightForWidth())
        self.c13.setSizePolicy(sizePolicy)
        self.c13.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c13.setFont(font)
        self.c13.setStyleSheet(_fromUtf8("border-image: url("+self.direccionDeImagenes+"cGris.png) 0 0 0 0 stretch stretch;"))
        self.c13.setObjectName(_fromUtf8("c13"))
        self.gridLayout_13.addWidget(self.c13, 0, 0, 2, 1)
        self.label_26 = QtGui.QLabel(self.Gcelda_109)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_13.addWidget(self.label_26, 0, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.Gcelda_109)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_13.addWidget(self.label_27, 1, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.Gcelda_109)
        self.Gcelda_110 = QtGui.QGroupBox(self.Grilla)
        self.Gcelda_110.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_110.sizePolicy().hasHeightForWidth())
        self.Gcelda_110.setSizePolicy(sizePolicy)
        self.Gcelda_110.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_110.setTitle(_fromUtf8(""))
        self.Gcelda_110.setObjectName(_fromUtf8("Gcelda_110"))
        self.gridLayout_14 = QtGui.QGridLayout(self.Gcelda_110)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.c14 = QtGui.QPushButton(self.Gcelda_110)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c14.sizePolicy().hasHeightForWidth())
        self.c14.setSizePolicy(sizePolicy)
        self.c14.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c14.setFont(font)
        self.c14.setStyleSheet(_fromUtf8("border-image: url("+self.direccionDeImagenes+"cGris.png) 0 0 0 0 stretch stretch;"))
        self.c14.setObjectName(_fromUtf8("c14"))
        self.gridLayout_14.addWidget(self.c14, 0, 0, 2, 1)
        self.label_28 = QtGui.QLabel(self.Gcelda_110)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_14.addWidget(self.label_28, 0, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.Gcelda_110)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_14.addWidget(self.label_29, 1, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.Gcelda_110)
        self.Gcelda_111 = QtGui.QGroupBox(self.Grilla)
        self.Gcelda_111.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_111.sizePolicy().hasHeightForWidth())
        self.Gcelda_111.setSizePolicy(sizePolicy)
        self.Gcelda_111.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_111.setTitle(_fromUtf8(""))
        self.Gcelda_111.setObjectName(_fromUtf8("Gcelda_111"))
        self.gridLayout_15 = QtGui.QGridLayout(self.Gcelda_111)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.c15 = QtGui.QPushButton(self.Gcelda_111)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c15.sizePolicy().hasHeightForWidth())
        self.c15.setSizePolicy(sizePolicy)
        self.c15.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c15.setFont(font)
        self.c15.setStyleSheet(_fromUtf8("border-image: url("+self.direccionDeImagenes+"cGris.png) 0 0 0 0 stretch stretch;"))
        self.c15.setObjectName(_fromUtf8("c15"))
        self.gridLayout_15.addWidget(self.c15, 0, 0, 2, 1)
        self.label_30 = QtGui.QLabel(self.Gcelda_111)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_15.addWidget(self.label_30, 0, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.Gcelda_111)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_15.addWidget(self.label_31, 1, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.Gcelda_111)
        self.Gcelda_112 = QtGui.QGroupBox(self.Grilla)
        self.Gcelda_112.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_112.sizePolicy().hasHeightForWidth())
        self.Gcelda_112.setSizePolicy(sizePolicy)
        self.Gcelda_112.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_112.setTitle(_fromUtf8(""))
        self.Gcelda_112.setObjectName(_fromUtf8("Gcelda_112"))
        self.gridLayout_16 = QtGui.QGridLayout(self.Gcelda_112)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.c16 = QtGui.QPushButton(self.Gcelda_112)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c16.sizePolicy().hasHeightForWidth())
        self.c16.setSizePolicy(sizePolicy)
        self.c16.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c16.setFont(font)
        self.c16.setStyleSheet(_fromUtf8("border-image: url("+self.direccionDeImagenes+"cGris.png) 0 0 0 0 stretch stretch;"))
        self.c16.setObjectName(_fromUtf8("c16"))
        self.gridLayout_16.addWidget(self.c16, 0, 0, 2, 1)
        self.label_32 = QtGui.QLabel(self.Gcelda_112)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_16.addWidget(self.label_32, 0, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.Gcelda_112)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_16.addWidget(self.label_33, 1, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.Gcelda_112)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.Gcelda_113 = QtGui.QGroupBox(self.Grilla)
        self.Gcelda_113.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_113.sizePolicy().hasHeightForWidth())
        self.Gcelda_113.setSizePolicy(sizePolicy)
        self.Gcelda_113.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_113.setTitle(_fromUtf8(""))
        self.Gcelda_113.setObjectName(_fromUtf8("Gcelda_113"))
        self.gridLayout_17 = QtGui.QGridLayout(self.Gcelda_113)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.c17 = QtGui.QPushButton(self.Gcelda_113)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c17.sizePolicy().hasHeightForWidth())
        self.c17.setSizePolicy(sizePolicy)
        self.c17.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c17.setFont(font)
        self.c17.setStyleSheet(_fromUtf8("border-image: url("+self.direccionDeImagenes+"cGris.png) 0 0 0 0 stretch stretch;"))
        self.c17.setObjectName(_fromUtf8("c17"))
        self.gridLayout_17.addWidget(self.c17, 0, 0, 2, 1)
        self.label_34 = QtGui.QLabel(self.Gcelda_113)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_17.addWidget(self.label_34, 0, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.Gcelda_113)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_17.addWidget(self.label_35, 1, 1, 1, 1)
        self.horizontalLayout_5.addWidget(self.Gcelda_113)
        self.Gcelda_114 = QtGui.QGroupBox(self.Grilla)
        self.Gcelda_114.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_114.sizePolicy().hasHeightForWidth())
        self.Gcelda_114.setSizePolicy(sizePolicy)
        self.Gcelda_114.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_114.setTitle(_fromUtf8(""))
        self.Gcelda_114.setObjectName(_fromUtf8("Gcelda_114"))
        self.gridLayout_18 = QtGui.QGridLayout(self.Gcelda_114)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.c18 = QtGui.QPushButton(self.Gcelda_114)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c18.sizePolicy().hasHeightForWidth())
        self.c18.setSizePolicy(sizePolicy)
        self.c18.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c18.setFont(font)
        self.c18.setStyleSheet(_fromUtf8("border-image: url("+self.direccionDeImagenes+"cGris.png) 0 0 0 0 stretch stretch;"))
        self.c18.setObjectName(_fromUtf8("c18"))
        self.gridLayout_18.addWidget(self.c18, 0, 0, 2, 1)
        self.label_36 = QtGui.QLabel(self.Gcelda_114)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_18.addWidget(self.label_36, 0, 1, 1, 1)
        self.label_37 = QtGui.QLabel(self.Gcelda_114)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_18.addWidget(self.label_37, 1, 1, 1, 1)
        self.horizontalLayout_5.addWidget(self.Gcelda_114)
        self.Gcelda_115 = QtGui.QGroupBox(self.Grilla)
        self.Gcelda_115.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_115.sizePolicy().hasHeightForWidth())
        self.Gcelda_115.setSizePolicy(sizePolicy)
        self.Gcelda_115.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_115.setTitle(_fromUtf8(""))
        self.Gcelda_115.setObjectName(_fromUtf8("Gcelda_115"))
        self.gridLayout_19 = QtGui.QGridLayout(self.Gcelda_115)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.c19 = QtGui.QPushButton(self.Gcelda_115)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c19.sizePolicy().hasHeightForWidth())
        self.c19.setSizePolicy(sizePolicy)
        self.c19.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c19.setFont(font)
        self.c19.setStyleSheet(_fromUtf8("border-image: url("+self.direccionDeImagenes+"cGris.png) 0 0 0 0 stretch stretch;"))
        self.c19.setObjectName(_fromUtf8("c19"))
        self.gridLayout_19.addWidget(self.c19, 0, 0, 2, 1)
        self.label_38 = QtGui.QLabel(self.Gcelda_115)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_19.addWidget(self.label_38, 0, 1, 1, 1)
        self.label_39 = QtGui.QLabel(self.Gcelda_115)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_19.addWidget(self.label_39, 1, 1, 1, 1)
        self.horizontalLayout_5.addWidget(self.Gcelda_115)
        self.Gcelda_116 = QtGui.QGroupBox(self.Grilla)
        self.Gcelda_116.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_116.sizePolicy().hasHeightForWidth())
        self.Gcelda_116.setSizePolicy(sizePolicy)
        self.Gcelda_116.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_116.setTitle(_fromUtf8(""))
        self.Gcelda_116.setObjectName(_fromUtf8("Gcelda_116"))
        self.gridLayout_20 = QtGui.QGridLayout(self.Gcelda_116)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.label_40 = QtGui.QLabel(self.Gcelda_116)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_20.addWidget(self.label_40, 0, 1, 1, 1)
        self.label_41 = QtGui.QLabel(self.Gcelda_116)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_20.addWidget(self.label_41, 1, 1, 1, 1)
        self.c20 = QtGui.QPushButton(self.Gcelda_116)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c20.sizePolicy().hasHeightForWidth())
        self.c20.setSizePolicy(sizePolicy)
        self.c20.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c20.setFont(font)
        self.c20.setStyleSheet(_fromUtf8("border-image: url("+self.direccionDeImagenes+"cGris.png) 0 0 0 0 stretch stretch;"))
        self.c20.setObjectName(_fromUtf8("c20"))
        self.gridLayout_20.addWidget(self.c20, 0, 0, 2, 1)
        self.horizontalLayout_5.addWidget(self.Gcelda_116)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12.addWidget(self.Grilla)
        self.groupBox = QtGui.QGroupBox(self.ContenedorGeneral)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(201, 0))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.referenciaPositivo = QtGui.QGroupBox(self.groupBox)
        self.referenciaPositivo.setStyleSheet(_fromUtf8("border: 1px solid black;"))
        self.referenciaPositivo.setTitle(_fromUtf8(""))
        self.referenciaPositivo.setObjectName(_fromUtf8("referenciaPositivo"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.referenciaPositivo)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.Gcelda_147 = QtGui.QGroupBox(self.referenciaPositivo)
        self.Gcelda_147.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_147.sizePolicy().hasHeightForWidth())
        self.Gcelda_147.setSizePolicy(sizePolicy)
        self.Gcelda_147.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_147.setTitle(_fromUtf8(""))
        self.Gcelda_147.setObjectName(_fromUtf8("Gcelda_147"))
        self.gridLayout_51 = QtGui.QGridLayout(self.Gcelda_147)
        self.gridLayout_51.setObjectName(_fromUtf8("gridLayout_51"))
        self.a1_2 = QtGui.QPushButton(self.Gcelda_147)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a1_2.sizePolicy().hasHeightForWidth())
        self.a1_2.setSizePolicy(sizePolicy)
        self.a1_2.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.a1_2.setFont(font)
        self.a1_2.setStyleSheet(_fromUtf8("border-image: url(" + self.direccionDeImagenes +"cRojo.png) 0 0 0 0 stretch stretch;"))
        self.a1_2.setObjectName(_fromUtf8("a1_2"))
        self.gridLayout_51.addWidget(self.a1_2, 0, 0, 2, 1)
        self.label_105 = QtGui.QLabel(self.Gcelda_147)
        self.label_105.setMinimumSize(QtCore.QSize(90, 0))
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.gridLayout_51.addWidget(self.label_105, 0, 1, 1, 1)
        self.horizontalLayout_13.addWidget(self.Gcelda_147)
        self.verticalLayout_4.addWidget(self.referenciaPositivo)
        self.referenciaNegativo = QtGui.QGroupBox(self.groupBox)
        self.referenciaNegativo.setStyleSheet(_fromUtf8("border: 1px solid black;"))
        self.referenciaNegativo.setTitle(_fromUtf8(""))
        self.referenciaNegativo.setObjectName(_fromUtf8("referenciaNegativo"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.referenciaNegativo)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.Gcelda_148 = QtGui.QGroupBox(self.referenciaNegativo)
        self.Gcelda_148.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_148.sizePolicy().hasHeightForWidth())
        self.Gcelda_148.setSizePolicy(sizePolicy)
        self.Gcelda_148.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_148.setTitle(_fromUtf8(""))
        self.Gcelda_148.setObjectName(_fromUtf8("Gcelda_148"))
        self.gridLayout_52 = QtGui.QGridLayout(self.Gcelda_148)
        self.gridLayout_52.setObjectName(_fromUtf8("gridLayout_52"))
        self.a1_3 = QtGui.QPushButton(self.Gcelda_148)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a1_3.sizePolicy().hasHeightForWidth())
        self.a1_3.setSizePolicy(sizePolicy)
        self.a1_3.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.a1_3.setFont(font)
        self.a1_3.setStyleSheet(_fromUtf8("border-image: url(" + self.direccionDeImagenes +"cVerde.png) 0 0 0 0 stretch stretch;"))
        self.a1_3.setObjectName(_fromUtf8("a1_3"))
        self.gridLayout_52.addWidget(self.a1_3, 0, 0, 2, 1)
        self.label_106 = QtGui.QLabel(self.Gcelda_148)
        self.label_106.setMinimumSize(QtCore.QSize(90, 0))
        self.label_106.setObjectName(_fromUtf8("label_106"))
        self.gridLayout_52.addWidget(self.label_106, 0, 1, 1, 1)
        self.horizontalLayout_14.addWidget(self.Gcelda_148)
        self.verticalLayout_4.addWidget(self.referenciaNegativo)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setStyleSheet(_fromUtf8("border: 1px solid black;"))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.Gcelda_150 = QtGui.QGroupBox(self.groupBox_2)
        self.Gcelda_150.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_150.sizePolicy().hasHeightForWidth())
        self.Gcelda_150.setSizePolicy(sizePolicy)
        self.Gcelda_150.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_150.setTitle(_fromUtf8(""))
        self.Gcelda_150.setObjectName(_fromUtf8("Gcelda_150"))
        self.gridLayout_54 = QtGui.QGridLayout(self.Gcelda_150)
        self.gridLayout_54.setObjectName(_fromUtf8("gridLayout_54"))
        self.a1_5 = QtGui.QPushButton(self.Gcelda_150)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a1_5.sizePolicy().hasHeightForWidth())
        self.a1_5.setSizePolicy(sizePolicy)
        self.a1_5.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.a1_5.setFont(font)
        self.a1_5.setStyleSheet(_fromUtf8("border-image: url(" + self.direccionDeImagenes +"cAmarillo) 0 0 0 0 stretch stretch;"))
        self.a1_5.setObjectName(_fromUtf8("a1_5"))
        self.gridLayout_54.addWidget(self.a1_5, 0, 0, 2, 1)
        self.label_108 = QtGui.QLabel(self.Gcelda_150)
        self.label_108.setMinimumSize(QtCore.QSize(90, 0))
        self.label_108.setObjectName(_fromUtf8("label_108"))
        self.gridLayout_54.addWidget(self.label_108, 0, 1, 1, 1)
        self.horizontalLayout_16.addWidget(self.Gcelda_150)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setStyleSheet(_fromUtf8("border: 1px solid black;"))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.Gcelda_151 = QtGui.QGroupBox(self.groupBox_4)
        self.Gcelda_151.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_151.sizePolicy().hasHeightForWidth())
        self.Gcelda_151.setSizePolicy(sizePolicy)
        self.Gcelda_151.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_151.setTitle(_fromUtf8(""))
        self.Gcelda_151.setObjectName(_fromUtf8("Gcelda_151"))
        self.gridLayout_55 = QtGui.QGridLayout(self.Gcelda_151)
        self.gridLayout_55.setObjectName(_fromUtf8("gridLayout_55"))
        self.label_109 = QtGui.QLabel(self.Gcelda_151)
        self.label_109.setMinimumSize(QtCore.QSize(90, 0))
        self.label_109.setObjectName(_fromUtf8("label_109"))
        self.gridLayout_55.addWidget(self.label_109, 0, 0, 1, 1)
        self.horizontalLayout_17.addWidget(self.Gcelda_151)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        spacerItem1 = QtGui.QSpacerItem(20, 233, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.referenciaVacio = QtGui.QGroupBox(self.groupBox)
        self.referenciaVacio.setStyleSheet(_fromUtf8("border: 1px solid black;"))
        self.referenciaVacio.setTitle(_fromUtf8(""))
        self.referenciaVacio.setObjectName(_fromUtf8("referenciaVacio"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.referenciaVacio)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.Gcelda_149 = QtGui.QGroupBox(self.referenciaVacio)
        self.Gcelda_149.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gcelda_149.sizePolicy().hasHeightForWidth())
        self.Gcelda_149.setSizePolicy(sizePolicy)
        self.Gcelda_149.setStyleSheet(_fromUtf8("border-color: rgb(255,255,255);\n"
"border-width: 1 px; \n"
"border-style: dashed;\n"
""))
        self.Gcelda_149.setTitle(_fromUtf8(""))
        self.Gcelda_149.setObjectName(_fromUtf8("Gcelda_149"))
        self.gridLayout_53 = QtGui.QGridLayout(self.Gcelda_149)
        self.gridLayout_53.setObjectName(_fromUtf8("gridLayout_53"))
        self.a1_4 = QtGui.QPushButton(self.Gcelda_149)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a1_4.sizePolicy().hasHeightForWidth())
        self.a1_4.setSizePolicy(sizePolicy)
        self.a1_4.setSizeIncrement(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.a1_4.setFont(font)
        self.a1_4.setStyleSheet(_fromUtf8("border-image: url(" + self.direccionDeImagenes +"cGris.png) 0 0 0 0 stretch stretch;"))
        self.a1_4.setObjectName(_fromUtf8("a1_4"))
        self.gridLayout_53.addWidget(self.a1_4, 0, 0, 2, 1)
        self.label_107 = QtGui.QLabel(self.Gcelda_149)
        self.label_107.setMinimumSize(QtCore.QSize(90, 0))
        self.label_107.setObjectName(_fromUtf8("label_107"))
        self.gridLayout_53.addWidget(self.label_107, 0, 1, 1, 1)
        self.horizontalLayout_15.addWidget(self.Gcelda_149)
        self.verticalLayout_4.addWidget(self.referenciaVacio)
        self.nuevoHemocultivo = QtGui.QPushButton(self.groupBox)
        self.nuevoHemocultivo.setMinimumSize(QtCore.QSize(0, 75))
        self.nuevoHemocultivo.setObjectName(_fromUtf8("nuevoHemocultivo"))
        self.verticalLayout_4.addWidget(self.nuevoHemocultivo)
        self.horizontalLayout_12.addWidget(self.groupBox)
        self.horizontalLayout_10.addWidget(self.ContenedorGeneral)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionUsuarios = QtGui.QAction(MainWindow)
        self.actionUsuarios.setObjectName(_fromUtf8("actionUsuarios"))

        self.retranslateUi(MainWindow)

        ####################################################################################################

        self.celdas= [self.c1, self.c2, self.c3, self.c4, self.c5,self.c6,self.c7,self.c8,self.c9,self.c10,
            self.c11,self.c12,self.c13,self.c14,self.c15,self.c16,self.c17,self.c18,self.c19,self.c20]#,
           # self.c21,self.c22, self.c23,self.c24,self.c25,self.c26,self.c27,self.c28,self.c29,self.c30,
           # self.c31,self.c32,self.c33,self.c34,self.c35,self.c36, self.c37, self.c38, self.c39, self.c40,
           # self.c41,self.c42, self.c43,self.c44, self.c45, self.c46, self.c47, self.c48, self.c49, self.c50 ]

        self.etiquetas = [ self.label_2, self.label_3, self.label_4, self.label_5, self.label_6, self.label_7, self.label_8, self.label_9, self.label_10,
                          self.label_11, self.label_12, self.label_13, self.label_14, self.label_15, self.label_16, self.label_17, self.label_18, self.label_19, self.label_20,
                          self.label_21, self.label_22, self.label_23, self.label_24, self.label_25, self.label_26, self.label_27, self.label_28, self.label_29, self.label_30,
                          self.label_31, self.label_32, self.label_33, self.label_34, self.label_35, self.label_36, self.label_37, self.label_38, self.label_39, self.label_40,
                          self.label_41]#, self.label_42, self.label_43, self.label_44, self.label_45, self.label_46, self.label_47, self.label_48, self.label_49, self.label_50,
                          #self.label_51, self.label_52, self.label_53, self.label_54, self.label_55, self.label_56, self.label_57, self.label_58, self.label_59, self.label_60,
                          #self.label_61, self.label_62, self.label_63, self.label_64, self.label_65, self.label_66, self.label_67, self.label_68, self.label_69, self.label_70,
                          #self.label_71, self.label_72, self.label_73, self.label_74, self.label_75, self.label_76, self.label_77, self.label_78, self.label_79, self.label_80,
                          #self.label_81, self.label_82, self.label_83, self.label_84, self.label_85, self.label_86, self.label_87, self.label_88, self.label_89, self.label_90,
                          #self.label_91, self.label_92, self.label_93, self.label_94, self.label_95, self.label_96, self.label_97, self.label_98, self.label_99, self.label_100, self.label_101]


        self.lcdNumber.setNumDigits(4)
        self.vm = VentanaMuestra()
        self.listadeventanasPositivas = []
        self.listadevantanasNegativas = []
        self.vh = VentanaHemocultivo()

        self.c=40
        self.temporizador()
        self.cvp = ControladorVentanaPrincipal()
        self.etiquetasEnBlanco()
        self.lineEdit_2.setEchoMode(QLineEdit.Password)

        icon2 = QtGui.QIcon(self.direccionDeImagenes + "/add.png")
        self.nuevoHemocultivo.setIcon(icon2)
        self.nuevoHemocultivo.setIconSize(QSize(30,30))

        iconUsuarios = QtGui.QIcon(self.direccionDeImagenes + "/usuarios.png")
        self.BUsuariosSettings.setIcon(iconUsuarios)
        self.BUsuariosSettings.setIconSize(QSize(30,30))

        iconMuestras = QtGui.QIcon(self.direccionDeImagenes + "/muestras.png")
        self.BInformesSettings.setIcon(iconMuestras)
        self.BInformesSettings.setIconSize(QSize(30,30))

        #iconAlarmas = QtGui.QIcon(self.direccionDeImagenes + "/alarmas.png")
        #self.BAlarmasSettings.setIcon(iconAlarmas)
        #self.BAlarmasSettings.setIconSize(QSize(30,30))

        iconCerrar = QtGui.QIcon(self.direccionDeImagenes +"/cerrarsesion.png")
        self.BLogOutSettings.setIcon(iconCerrar)
        self.BLogOutSettings.setIconSize(QSize(30,30))

        iconIniciar = QtGui.QIcon(self.direccionDeImagenes + "/iniciarsesion.png")
        self.Submit.setIcon(iconIniciar)
        self.Submit.setIconSize(QSize(30,30))
###      Botones Grilla ON CLick   Celdas


        for i in self.celdas:

            QtCore.QObject.connect(i, QtCore.SIGNAL(_fromUtf8("clicked()")),self.llamadorVentanaCelda)

### Boton Nuevo Hemocultivo
        QtCore.QObject.connect(self.nuevoHemocultivo, QtCore.SIGNAL(_fromUtf8("clicked()")),self.llamadorVentanaHemocultivo)

###   Botones Settingsss
        QtCore.QObject.connect(self.BUsuariosSettings, QtCore.SIGNAL(_fromUtf8("clicked()")),self.llamadorVentanaUsuario)
        QtCore.QObject.connect(self.BInformesSettings, QtCore.SIGNAL(_fromUtf8("clicked()")), self.llamadorVentanaMuestras)
        QtCore.QObject.connect(self.Submit, QtCore.SIGNAL(_fromUtf8("clicked()")), self.login)
        QtCore.QObject.connect(self.BLogOutSettings, QtCore.SIGNAL(_fromUtf8("clicked()")), self.logout)
        QtCore.QObject.connect(self.BUsuariosSettings, QtCore.SIGNAL(_fromUtf8("clicked()")), self.Gcelda_100.showFullScreen)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.celdasEnFlag = {}
        self.celdasEnAlarma= {}
        self.logout()

    def llamadorVentanaHemocultivo(self):
        self.vh = VentanaHemocultivo()
        self.vh.__init__()
        self.vh.show()

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Biomen", None))
        self.GLogIn.setTitle(_translate("MainWindow", "LogIn", None))
        self.label_103.setText(_translate("MainWindow", "Usuario", None))
        self.label_104.setText(_translate("MainWindow", "Password", None))
        self.Submit.setText(_translate("MainWindow", "Iniciar Sesion", None))
        self.BInformesSettings.setText(_translate("MainWindow", "Muestra", None))
        self.BUsuariosSettings.setText(_translate("MainWindow", "Usuario", None))
        self.BLogOutSettings.setText(_translate("MainWindow", "Cerrar Sesion", None))
        self.label.setText(_translate("MainWindow", "Temperatura", None))
        self.c1.setText(_translate("MainWindow", "1", None))
        self.label_3.setText(_translate("MainWindow", "hh:mm", None))
        self.label_2.setText(_translate("MainWindow", "dd/mm/aaaa", None))
        self.label_4.setText(_translate("MainWindow", "TextLabel", None))
        self.label_5.setText(_translate("MainWindow", "TextLabel", None))
        self.c2.setText(_translate("MainWindow", "2", None))
        self.c3.setText(_translate("MainWindow", "3", None))
        self.label_6.setText(_translate("MainWindow", "TextLabel", None))
        self.label_7.setText(_translate("MainWindow", "TextLabel", None))
        self.c4.setText(_translate("MainWindow", "4", None))
        self.label_8.setText(_translate("MainWindow", "TextLabel", None))
        self.label_9.setText(_translate("MainWindow", "TextLabel", None))
        self.label_10.setText(_translate("MainWindow", "TextLabel", None))
        self.label_11.setText(_translate("MainWindow", "TextLabel", None))
        self.c5.setText(_translate("MainWindow", "5", None))
        self.c6.setText(_translate("MainWindow", "6", None))
        self.label_12.setText(_translate("MainWindow", "TextLabel", None))
        self.label_13.setText(_translate("MainWindow", "TextLabel", None))
        self.c7.setText(_translate("MainWindow", "7", None))
        self.label_14.setText(_translate("MainWindow", "TextLabel", None))
        self.label_15.setText(_translate("MainWindow", "TextLabel", None))
        self.c8.setText(_translate("MainWindow", "8", None))
        self.label_16.setText(_translate("MainWindow", "TextLabel", None))
        self.label_17.setText(_translate("MainWindow", "TextLabel", None))
        self.c9.setText(_translate("MainWindow", "9", None))
        self.label_18.setText(_translate("MainWindow", "TextLabel", None))
        self.label_19.setText(_translate("MainWindow", "TextLabel", None))
        self.c10.setText(_translate("MainWindow", "10", None))
        self.label_20.setText(_translate("MainWindow", "TextLabel", None))
        self.label_21.setText(_translate("MainWindow", "TextLabel", None))
        self.c11.setText(_translate("MainWindow", "11", None))
        self.label_22.setText(_translate("MainWindow", "TextLabel", None))
        self.label_23.setText(_translate("MainWindow", "TextLabel", None))
        self.c12.setText(_translate("MainWindow", "12", None))
        self.label_24.setText(_translate("MainWindow", "TextLabel", None))
        self.label_25.setText(_translate("MainWindow", "TextLabel", None))
        self.c14.setText(_translate("MainWindow", "14", None))
        self.label_28.setText(_translate("MainWindow", "TextLabel", None))
        self.label_29.setText(_translate("MainWindow", "TextLabel", None))
        self.c13.setText(_translate("MainWindow", "13", None))
        self.label_26.setText(_translate("MainWindow", "TextLabel", None))
        self.label_27.setText(_translate("MainWindow", "TextLabel", None))
        self.c15.setText(_translate("MainWindow", "15", None))
        self.label_30.setText(_translate("MainWindow", "TextLabel", None))
        self.label_31.setText(_translate("MainWindow", "TextLabel", None))
        self.c16.setText(_translate("MainWindow", "16", None))
        self.label_32.setText(_translate("MainWindow", "TextLabel", None))
        self.label_33.setText(_translate("MainWindow", "TextLabel", None))
        self.c17.setText(_translate("MainWindow", "17", None))
        self.label_34.setText(_translate("MainWindow", "TextLabel", None))
        self.label_35.setText(_translate("MainWindow", "TextLabel", None))
        self.c18.setText(_translate("MainWindow", "18", None))
        self.label_36.setText(_translate("MainWindow", "TextLabel", None))
        self.label_37.setText(_translate("MainWindow", "TextLabel", None))
        self.c19.setText(_translate("MainWindow", "19", None))
        self.label_38.setText(_translate("MainWindow", "TextLabel", None))
        self.label_39.setText(_translate("MainWindow", "TextLabel", None))
        self.label_40.setText(_translate("MainWindow", "TextLabel", None))
        self.label_41.setText(_translate("MainWindow", "TextLabel", None))
        self.c20.setText(_translate("MainWindow", "20", None))
        self.groupBox.setTitle(_translate("MainWindow", "Balance", None))
        self.a1_2.setText(_translate("MainWindow", "0", None))
        self.label_105.setText(_translate("MainWindow", "Positivo  ", None))
        self.a1_3.setText(_translate("MainWindow", "0", None))
        self.label_106.setText(_translate("MainWindow", "Negativo  ", None))
        self.a1_5.setText(_translate("MainWindow", "0", None))
        self.label_108.setText(_translate("MainWindow", "En Proceso", None))
        self.label_109.setText(_translate("MainWindow", "Total Ocupados      0", None))
        self.a1_4.setText(_translate("MainWindow", "0", None))
        self.label_107.setText(_translate("MainWindow", "Desocupado", None))
        self.nuevoHemocultivo.setText(_translate("MainWindow", "Ingresar Muestra", None))
        self.actionUsuarios.setText(_translate("MainWindow", "Usuarios", None))

    def windowActivationChange(self, bool):
        if self.isActiveWindow():
            self.c = 30
            if self.timer.isActive()== False:
                self.timer.start()

    def llamadorVentanaCelda(self):
            if self.usuario == " ":
                QMessageBox.warning(self,"Error", "Por favor, iniciar sesion", QMessageBox.Ok)
            else:
                try:
                    self.timer.stop()
                    from Vista.VentanCelda import VentanaCelda
                    a = self.sender().objectName()
                    self.vc = VentanaCelda(self)
                    if self.vc.obtenerCelda(a) == 0:
                        QMessageBox.warning(self," ", "Celda vacia", QMessageBox.Ok)
                    else:
                        self.vc.showFullScreen()
                        self.vc.graficar()
                        self.vc.obtenerDatos()
                except IndexError:
                    self.vc.close()
                    QMessageBox.warning(self," ", "Error al cargar los detalles de la muestra", QMessageBox.Ok)

    def llamadorVentanaMuestras(self):
        self.vm = VentanaMuestra()
        self.vm.showFullScreen()

    def llamadorVentanaUsuario(self):
        self.vu = VentanaUsuario()
        self.vu.obtenerUsuario(self.usuario)
        self.vu.show()

    def login(self):
            u = self.lineEdit.text()
            p = self.lineEdit_2.text()                                                                                    # si lineedit1 es distinto de vacio se compara el campo pass con el pass de la base Where username = lineedit1
            if u and p != "":
                if self.cvp.passUsuario(u)== None:
                    QMessageBox.warning(self,"Error", "Usuario Inexistente", QMessageBox.Ok)

                elif p == self.cvp.passUsuario(u):
                    self.nuevoHemocultivo.setEnabled(True)
                    self.Settings.setEnabled(True)
                    #self.BAlarmasSettings.setEnabled(False)
                    self.GLogIn.close()
                    self.lineEdit.clear()                                                                                    # se vacian los line Edit
                    self.lineEdit_2.clear()
                    self.usuario = u
                    self.vh.obtenerUsuario(self.usuario)                                                # se pasa el username del usuario logueado a las ventanas usuario y hemocultivo
                    #self.colorEstado()
                else:                                                                                                                          # mesaje de error de login
                    QMessageBox.warning(self,"Error", "Clave Incorrecta", QMessageBox.Ok)
            else:                                                                                                                           # mensaje de error de campos vacios
                QMessageBox.warning(self,"Error", "'ingrese usuario y clave'", QMessageBox.Ok)

    def logout(self):
        self.usuario = " "                                                                                                         # se vacia la variale que almacena el usuario logueado
        self.nuevoHemocultivo.setEnabled(False)                                           # se ponen en disabled todas las opciones de la ventana principal y se vuelve a mostrar el grup logIn
        self.Settings.setEnabled(False)
        self.GLogIn.showFullScreen()
                                                                        # todas las celdas desabilitadas

    def temporizador(self, valor=1000):
        self.timer= QtCore.QTimer(self)
        self.timer.timeout.connect(self.refrescar)
        if self.timer.isActive() == False:
            self.timer.start(valor)
        else:
            self.timer.setInterval(valor)

    def refrescar(self):

        if self.c!=30 and len(self.celdasEnAlarma)!= 0 :
            self.upiteoAlarma()
        elif self.c == 30:
            self.colorEstado()
            self.c=0
        self.c = self.c + 1

    def temperaturaLCD(self, temperatura):

        if temperatura > 36.9:
            self.lcdNumber.setStyleSheet("color: rgb(255, 0, 0);")

            palette = QtGui.QPalette()
            palette.setColor(QtGui.QPalette.Foreground,QtCore.Qt.red)
            self.label.setText("ATENCION:\ntemperatura\nmuy elevada".upper())

            self.label.setPalette(palette)

        elif temperatura < 35.9:
            self.lcdNumber.setStyleSheet("color: rgb(0, 0, 255);")
            palette = QtGui.QPalette()
            palette.setColor(QtGui.QPalette.Foreground,QtCore.Qt.black)
            self.label.setText(_translate("MainWindow", "Temperatura:", None))
            self.label.setPalette(palette)
        else:
            self.lcdNumber.setStyleSheet("color: rgb(0, 255, 0);")
            palette = QtGui.QPalette()
            palette.setColor(QtGui.QPalette.Foreground,QtCore.Qt.black)
            self.label.setText(_translate("MainWindow", "Temperatura:", None))
            self.label.setPalette(palette)
        self.lcdNumber.display(temperatura)

    def colorEstado(self):
        self.listadeventanasPositivas = []
        self.listadevantanasNegativas = []
        from VentanitaPositivo import VentanaPositivo
        temperatura = self.cvp.temperatura()[0]
        self.temperaturaLCD(temperatura)
        self.etiquetasEnBlanco()
        desocupado = 0
        positivo = 0
        negativo = 0
        proceso = 0
        ############## consulto datos ############
        datos = self.cvp.cambiar()
        for j in datos:
                color = j [0]
                fecha=j[1]
                hora = str(j[2])
                self.valorAlarma = j[3]
                self.celdas[j[4]-1].setStyleSheet(_fromUtf8("border-image: url(" + self.direccionDeImagenes +color+") 0 0 0 0 stretch stretch;"))
              ################# manejo celdas en alarma ####################
                self.manejoAlarma(j[4]-1,self.valorAlarma,color)
             ############## si  esta ocupada la celda, muestra los labels de fecha de ingreso y tiempo trascurrido #######
                if color != "cGris" :
                    self.etiquetas[(j[4]-1) * 2].setText(fecha)
                    self.etiquetas[((j[4]-1) * 2) + 1].setText(hora)
                    if self.usuario != " ":
                        self.celdas[j[4]-1].setEnabled(True)
                        ########### depende el color se actualiza el contador  y el estado de las celdas ###########
                if color == "cGris":
                    #self.celdas[j[4]-1].setEnabled(False)
                    if self.celdas[j[4]-1] in self.diccionarioPositivo:
                        self.diccionarioPositivo.remove(self.celdas[j[4]-1])
                    desocupado += 1

                if color == "cVerde":

                    if self.celdas[j[4]-1] not in self.diccionarioNegativo:
                        if self.cvp.estadoAceptado(j[5]) == False:

                            texto ="    Negativo detectado en celda  " + str( j[4])
                            colorNegativo = "border-color: rgb(0, 255, 0);background-color: rgb(0, 255  0);"
                            van= VentanaPositivo(j[4], texto, colorNegativo)
                            van.showFullScreen()
                            self.listadevantanasNegativas.append(van)
                        self.diccionarioNegativo.append(self.celdas[j[4]-1])
                    negativo +=1

                if color == "cRojo":
                    if self.celdas[j[4]-1] not in self.diccionarioPositivo:
                        if self.cvp.estadoAceptado(j[5]) == False:

                            texto ="    Positivo detectado en celda : " + str( j[4])
                            colorPositivo = "border-color: rgb(255, 0, 0);background-color: rgb(255, 0, 0);"
                            vap= VentanaPositivo(j[4], texto, colorPositivo)
                            vap.showFullScreen()
                            self.listadeventanasPositivas.append(vap)
                        self.diccionarioPositivo.append(self.celdas[j[4]-1])
                    positivo+=1

                if color == "cAmarillo":
                    proceso += 1
                self.label_109.setText("Total ocupados = "+str(negativo+positivo+proceso))
                self.a1_3.setText(str(negativo))
                self.a1_2.setText(str(positivo))
                self.a1_4.setText(str(desocupado))
                self.a1_5.setText(str(proceso))

    def manejoAlarma(self,celda,valorAlarma,color):
        if valorAlarma == 1 :
                if celda not in self.celdasEnAlarma :
                        self.celdasEnAlarma[celda] = color
                        self.celdasEnFlag[celda] = False
                else :
                    self.celdasEnAlarma[celda] = color
                    self.celdasEnFlag[celda] = True
        if self.valorAlarma == 0:
                if celda in self.celdasEnAlarma :
                    del self.celdasEnAlarma[celda]

    def upiteoAlarma(self):

            for i in self.celdasEnAlarma :
                if self.celdasEnFlag[i] == False:
                    self.celdas[i].setStyleSheet(_fromUtf8("border-image: url("+self.direccionDeImagenes+self.celdasEnAlarma[i]+") 0 0 0 0 stretch stretch;"))
                    self.celdasEnFlag[i] = True
                else:
                    self.celdas[i].setStyleSheet(_fromUtf8("border-image: url(" + self.direccionDeImagenes + "cAlarma) 0 0 0 0 stretch stretch;"))
                    self.celdasEnFlag[i] = False

    def etiquetasEnBlanco(self):
        for i in self.etiquetas:
            i.setText('                         ')
